### ISSUE TITLE
Strange escapes with LaTex math env formulas in Excel table 

### ISSUE THREAD

**Issue by faberchri** [eric-wood/excel2latex#11]
```
\begin{tabular}{ | l | l | l | l | }
\hline
    \$\\mathrm\{X\^\{-\}\}\$ (M) & foo  & bar & baz \\ \hline
\end{tabular}
```

**Comment by TheJBR** [comment]
This request may be old, but how about a simple switch to completely disable escaping characters?

This way, for raw data everything remains safe, while if you decide to do escaping yourself you can do so.

**Comment by eric-wood** [comment]
that's a reasonable compromise. I'll look into adding that sometime this week!
