### ISSUE TITLE
[feature request]Converting color table in excel to latex code?

### ISSUE THREAD

**Issue by wangg12** [eric-wood/excel2latex#12]

**Comment by eric-wood** [comment]
Sorry I'm so late to respond to this one...could you elaborate? I'm about to do a rewrite and need to figure out what features to explore.

**Comment by wangg12** [comment]
For example, when converting the tables in excel to latex code, the plugin could provide an option to keep the color of foreground(the text) or the background(the cell) which has been created in excel.
